#!/bin/sh
# Regenerate `.loop/evidence/T-0092/git-diff.raw` — the bytes the diff parser's
# unit test `include_str!`s.
#
# **Why this is a script and not a one-off.** The fixture must be *git's actual
# output* (that is the whole point of the test), but a scratch repository under
# `target/` is temporary — the TUI slice wipes `target/test-scratch/T-0092` when
# it runs, which is how the first version of this fixture was lost and then
# silently committed with its carriage returns stripped by `* text=auto`. Two
# rules follow from that, and both are load-bearing:
#
#   1. `.loop/evidence/**/*.raw` is marked `-text` in `.gitattributes`, so git
#      never normalizes it. Without that the CRLF assertions pass locally and fail
#      on a fresh clone — the worst place to find out.
#   2. The repository is rebuilt from scratch here, covering every shape the diff
#      format has, so the fixture can be reproduced after any scratch wipe.
#
# Run from the repo root: `sh .loop/evidence/T-0092/regenerate.sh`, then
# `cargo test -p arreo-core --lib diff::` (the test parses this file) and
# `git add .loop/evidence/T-0092/git-diff.raw`.
set -eu

ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
WORK="$ROOT/target/test-scratch/T-0092-fixture"
RAW="$ROOT/.loop/evidence/T-0092/git-diff.raw"
BYTES="$ROOT/.loop/evidence/T-0092/git-diff-bytes.txt"

rm -rf "$WORK"
mkdir -p "$WORK"
cd "$WORK"
git init -q -b main
git config user.name "arreo fixture"
git config user.email "fixture@arreo.invalid"
# The default: non-ASCII paths are quoted with octal escapes. Pinned explicitly
# so the fixture does not depend on the machine's git config.
git config core.quotePath true

# ---- the base commit: every file the changes below touch ---------------------
printf 'one\ntwo\nthree\nfour\nfive\n' > modify.txt
printf 'keep me\n' > rename-me.txt
printf 'plain text\n' > both.txt
printf 'CRLF line\r\nsecond\r\n' > crlf.txt
printf 'no newline at end' > nonewline.txt
printf '\000\001\002binary\377\376' > blob.bin
printf 'to be deleted\n' > doomed.txt
printf 'x\ny\nz\n' > ctx.txt
git add .
git commit -qm base

# ---- the changes: one of every shape git emits -------------------------------
printf 'one\nTWO CHANGED\nthree\nfour\nfive\n' > modify.txt   # replace mid-hunk
git mv rename-me.txt renamed.txt                              # a pure rename (100%)
printf 'plain text\nwith an addition\n' > both.txt            # add + context
printf 'CRLF line\r\nsecond changed\r\nthird\r\n' > crlf.txt  # CRLF content
printf 'no newline at end (changed)' > nonewline.txt          # no trailing newline
printf '\000\001\002CHANGED\377\376' > blob.bin               # binary
rm doomed.txt                                                 # a deletion
printf 'brand new file\nsecond line\n' > added.txt            # a new file
printf 'x\n\ny\nCHANGED\n' > ctx.txt                          # an empty context line
printf 'x\n' > "my file.txt"                                  # a space in the name
printf 'x\n' > 'quote"name.txt'                               # a quote in the name
printf 'x\n' > "täb çhär.txt"                                 # non-ASCII in the name
git add -A

git diff --cached HEAD --no-color > "$RAW"

# The human-readable companion: the same bytes through `cat -A`, so the traps
# (^I for the trailing tab, ^M for a carriage return, $ for end of line) are
# visible to a reviewer who does not want to hexdump the fixture.
{
  echo "T-0092 — the real bytes the parser must handle (git $(git --version | awk '{print $3}'), captured on this box)"
  echo
  echo "Generated by .loop/evidence/T-0092/regenerate.sh; the raw bytes are the"
  echo "sibling git-diff.raw, which the unit test parses directly."
  echo
  echo "The 12 changes:"
  git status --porcelain | sed 's/^/  /'
  echo
  echo "===== cat -A of git-diff.raw (^I = TAB, ^M = CR, \$ = end of line) ====="
  cat -A "$RAW"
} > "$BYTES"

cd "$ROOT"
echo "wrote $RAW ($(wc -c < "$RAW") bytes, $(grep -c "$(printf '\r')" "$RAW" || true) carriage returns)"
echo "wrote $BYTES ($(wc -l < "$BYTES") lines)"
