[package]
name = "arreo-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "arreo"
path = "src/main.rs"

[dependencies]
arreo-core = { version = "0.1.0", path = "../arreo-core" }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync", "time", "io-util", "net"] }
